# Generated by Django 3.2.4 on 2021-06-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=20)),
                ('otp', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
