# Generated by Django 3.2.4 on 2021-07-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_alter_voter_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
