# Generated by Django 3.2.4 on 2021-07-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0005_auto_20210713_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='display_id',
        ),
        migrations.AddField(
            model_name='voter',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
