# Generated by Django 3.2.4 on 2021-07-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0006_auto_20210713_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='count',
        ),
        migrations.AddField(
            model_name='voter',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
