# Generated by Django 3.2.4 on 2021-07-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election_start_stop',
            fields=[
                ('index', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('Election_status', models.BooleanField()),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
